# Brain improvement on 3 Terrains (CMA-ES)
# takes Step_Curry brain and body. 
# population is generated by placing step curry and:
    # a gaussian around the elite.
    #  immigrants (rando)
    # some sparse

# Third-party libraries
import numpy as np
import torch
import json
from pathlib import Path
from evotorch import Problem
from evotorch.algorithms import CMAES
import matplotlib.pyplot as plt
import networkx as nx
import mujoco
from mujoco import mj_step, viewer
from rich.progress import track, Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn, TimeRemainingColumn

# ariel imports (ensure ariel is on PYTHONPATH)
from ariel.simulation.environments.olympic_arena import OlympicArena
from ariel.body_phenotypes.robogen_lite.modules.core import CoreModule
from ariel.body_phenotypes.robogen_lite.modules.brick import BrickModule
from ariel.body_phenotypes.robogen_lite.modules.hinge import HingeModule
from ariel.body_phenotypes.robogen_lite.config import ModuleFaces

# Settings 
JSON_PATH = Path(r"Robot_Result/Step_Curry.json") # BODY stays fixed
ELITE_BRAIN_JSON = Path(r"Robot_Result/Step_Curry_Brain.json")
POPULATION_SIZE = 50
GENERATIONS = 150
SIMULATION_STEPS = 7500
INITIAL_WEIGHT_RANGE = 1.0
HIDDEN_SIZE = 16
MAX_VELOCITY = 0.05
MAX_ANGLE = np.pi / 2
TIME_INPUTS = 2
position = [-0.8, 0, 0.1]  # kept for compatibility (not used directly for multi-terrain)
TARGET_POSITION = [5.0, 0.0, 0.5]  # Target to reach

#terrain spawns 
SPAWN_FLAT   = np.array([-2.40, 0.0, 0.10], dtype=np.float64)
SPAWN_RUGGED = np.array([-0.90, 0.0, 0.12], dtype=np.float64)
SPAWN_HILL   = np.array([ 2.65, 0.0, 0.12], dtype=np.float64)
TERRAIN_SPAWNS = (
    ("flat",   SPAWN_FLAT),
    ("rugged", SPAWN_RUGGED),
    ("hill",   SPAWN_HILL),
)

# Gen-0 population:
# elite + Gaussian around elite + immigrants + sparse
P_LOCAL = 0.60
P_IMM = 0.30
P_SPARSE = 0.10
SIGMA_LOCAL = 0.25 # fraction of INITIAL_WEIGHT_RANGE
SPARSE_FRAC = 0.15 # fraction of coordinates perturbed


# Helpers: JSON graph loader and robot constructor 
def load_graph_from_json(path: Path) -> nx.DiGraph:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    graph = nx.DiGraph()
    for node in data["nodes"]:
        graph.add_node(node["id"], type=node["type"], rotation=node.get("rotation", "DEG_0"))
    for edge in data["edges"]:
        graph.add_edge(edge["source"], edge["target"], face=edge["face"])
    return graph


def construct_core_from_graph(graph: nx.DiGraph):
    modules = {}
    for node_id, attrs in graph.nodes(data=True):
        node_type = attrs["type"]
        rotation = attrs.get("rotation", "DEG_0")
        if node_type == "CORE":
            modules[node_id] = CoreModule(index=node_id)
        elif node_type == "BRICK":
            modules[node_id] = BrickModule(index=node_id)
        elif node_type == "HINGE":
            modules[node_id] = HingeModule(index=node_id)
        else:
            modules[node_id] = None
        if node_type in ["HINGE", "BRICK"] and modules[node_id] is not None:
            try:
                deg = int(rotation.replace("DEG_", ""))
                modules[node_id].rotate(deg)
            except Exception:
                pass
    # attach bodies according to edges
    for src, tgt, edge_attrs in graph.edges(data=True):
        face = edge_attrs["face"]
        src_module = modules.get(src)
        tgt_module = modules.get(tgt)
        if src_module is None or tgt_module is None:
            continue
        try:
            src_module.sites[getattr(ModuleFaces, face)].attach_body(
                body=tgt_module.body,
                prefix=f"{tgt_module.__class__.__name__.lower()}_{tgt}"
            )
        except Exception:
            pass
    core_nodes = [nid for nid, attrs in graph.nodes(data=True) if attrs["type"] == "CORE"]
    if len(core_nodes) != 1:
        raise ValueError("Expected exactly one CORE module")
    return modules[core_nodes[0]], modules


# Decode genome 
def tanh(x):
    return np.tanh(x)


def normalize_qpos(qpos: np.ndarray) -> np.ndarray:
    # qpos are angles/positions; for angles normalise by pi to [-1,1]
    return np.clip(qpos / np.pi, -1.0, 1.0)


def normalize_xpos(xpos_flat: np.ndarray) -> np.ndarray:
    return np.clip(xpos_flat / 10.0, -1.0, 1.0)


def normalize_xmat(xmat_flat: np.ndarray) -> np.ndarray:
    return np.clip(xmat_flat, -1.0, 1.0)


def assemble_inputs_from_data(data, model):
    """
    COPY of your feature assembly but limited to core (as in your latest files):
    - qpos (NQ)
    - core xpos (3)
    - core xmat flattened (9)
    - time features added by caller
    """
    NQ = model.nq
    # qpos
    qpos = np.array(data.qpos[:NQ], dtype=np.float64)
    qpos_norm = normalize_qpos(qpos)
    # core body position
    try:
        xpos = np.array(data.xpos[0], dtype=np.float64)
    except Exception:
        xpos = np.zeros(3, dtype=np.float64)
    xpos_norm = normalize_xpos(xpos)
    # core body rotation matrix
    try:
        xmat = np.array(data.xmat[0].reshape(-1), dtype=np.float64)
    except Exception:
        xmat = np.zeros(9, dtype=np.float64)
    xmat_norm = normalize_xmat(xmat)
    features = np.concatenate([qpos_norm, xpos_norm, xmat_norm]).astype(np.float32)
    return features


def velocity_to_target(prev_ctrl: np.ndarray, raw_outputs: np.ndarray) -> np.ndarray:
    velocity = raw_outputs * MAX_VELOCITY
    new_ctrl = prev_ctrl + velocity
    return np.clip(new_ctrl, -MAX_ANGLE, MAX_ANGLE)


def decode_genome(genome, input_size, output_size):
    g = np.array(genome, dtype=np.float64)
    idx = 0
    W_in = g[idx: idx + input_size * HIDDEN_SIZE].reshape(input_size, HIDDEN_SIZE)
    idx += input_size * HIDDEN_SIZE
    W_rec = g[idx: idx + HIDDEN_SIZE * HIDDEN_SIZE].reshape(HIDDEN_SIZE, HIDDEN_SIZE)
    idx += HIDDEN_SIZE * HIDDEN_SIZE
    W_out = g[idx: idx + HIDDEN_SIZE * output_size].reshape(HIDDEN_SIZE, output_size)
    return W_in, W_rec, W_out


# Build sample model to determine sizes
robot_graph = load_graph_from_json(JSON_PATH)
core_for_dims, _ = construct_core_from_graph(robot_graph)
world_for_dims = OlympicArena()
world_for_dims.spawn(core_for_dims.spec, position=np.array(SPAWN_FLAT))  # NOTE: spawn_position

#ERROR POSITION
# world_for_dims.spawn(core_for_dims.spec, position=np.array(SPAWN_FLAT))

model_for_dims = world_for_dims.spec.compile()

NQ = int(model_for_dims.nq)
NU = int(model_for_dims.nu)
BASE_INPUT_SIZE = NQ + 3 + 9
INPUT_SIZE = BASE_INPUT_SIZE + TIME_INPUTS
OUTPUT_SIZE = NU
GENOME_SIZE = INPUT_SIZE * HIDDEN_SIZE + HIDDEN_SIZE * HIDDEN_SIZE + HIDDEN_SIZE * OUTPUT_SIZE


# target on terrains 
TARGET = np.array(TARGET_POSITION, dtype=np.float64)

def episode_progress(genome: np.ndarray, spawn_xyz: np.ndarray, steps: int, record_path=False) -> tuple:
    core, _ = construct_core_from_graph(robot_graph)
    world = OlympicArena()
    world.spawn(core.spec, position=np.array(spawn_xyz))

    #ERROR POSITION
    # world.spawn(core.spec, position=np.array(spawn_xyz))

    model = world.spec.compile()
    data = mujoco.MjData(model)

    mujoco.mj_resetData(model, data)
    data.qvel[:] = 0
    data.qacc[:] = 0
    mujoco.mj_forward(model, data)

    # unit direction from spawn to target
    spawn_vec = np.array(spawn_xyz, dtype=np.float64)
    dir_vec = TARGET - spawn_vec
    n = np.linalg.norm(dir_vec)
    u_dir = dir_vec / n if n > 1e-9 else np.array([1.0, 0.0, 0.0])

    W_in, W_rec, W_out = decode_genome(genome, INPUT_SIZE, OUTPUT_SIZE)
    h = np.zeros(HIDDEN_SIZE, dtype=np.float64)
    ctrl_state = np.zeros(OUTPUT_SIZE, dtype=np.float64)

    best_proj = 0.0
    path = [] if record_path else None

    for t in range(steps):
        base_feats = assemble_inputs_from_data(data, model)
        phase = 2 * np.pi * (t / steps)
        time_feats = np.array([np.sin(phase), np.cos(phase)], dtype=np.float32)
        inputs = np.concatenate([base_feats, time_feats]).astype(np.float64)

        h = tanh(np.dot(inputs, W_in) + np.dot(h, W_rec))
        raw_outputs = tanh(np.dot(h, W_out))
        ctrl_state = velocity_to_target(ctrl_state, raw_outputs)
        napply = min(len(data.ctrl), len(ctrl_state))
        data.ctrl[:napply] = ctrl_state[:napply]

        mj_step(model, data)

        try:
            p = np.array(data.xpos[0], dtype=np.float64)
        except Exception:
            p = spawn_vec
        
        # Record path if requested
        if record_path:
            path.append(p.copy())
            
        proj = float(np.dot(p - spawn_vec, u_dir))
        if proj > best_proj:
            best_proj = proj

    fitness = max(0.0, best_proj)
    if record_path:
        return fitness, path
    else:
        return fitness, None


# 3-terrain fitness wrapper
def evaluate_multi_terrain(genome: np.ndarray, steps: int, record_paths=False):
    comps = {}
    paths = {} if record_paths else None
    total = 0.0
    for name, spawn in TERRAIN_SPAWNS:
        fitness, path = episode_progress(genome, spawn, steps, record_path=record_paths)
        comps[name] = fitness
        if record_paths:
            paths[name] = path
        total += fitness
    if record_paths:
        return total, comps, paths
    else:
        return total, comps


# Evaluate wrapper for EvoTorch 
def evotorch_eval(genome: torch.Tensor) -> float:
    g = genome.detach().cpu().numpy().astype(np.float32)
    result = evaluate_multi_terrain(g, SIMULATION_STEPS)
    tot = result[0]  # First element is always total fitness
    return float(tot)


def clip_bounds(x: np.ndarray, W: float) -> np.ndarray:
    return np.clip(x, -W, W)


def make_gen0_population(elite: np.ndarray, popsize: int, W: float):
    out = [elite.copy()]  # slot 0 = elite
    d = elite.size

    n_local = int(P_LOCAL * popsize)
    n_imm = int(P_IMM * popsize)
    n_sparse = int(P_SPARSE * popsize)

    used = 1 + n_local + n_imm + n_sparse
    if used > popsize:
        overflow = used - popsize
        n_sparse = max(0, n_sparse - overflow)
    elif used < popsize:
        n_local += (popsize - used)

    sigma = SIGMA_LOCAL * W

    # Local Gaussian
    for _ in range(n_local):
        z = np.random.normal(0.0, sigma, size=d)
        out.append(clip_bounds(elite + z, W))

    # Immigrants (uniform)
    for _ in range(n_imm):
        out.append(np.random.uniform(-W, W, size=d))

    # Sparse perturbations
    k = max(1, int(SPARSE_FRAC * d))
    for _ in range(n_sparse):
        idx = np.random.choice(d, size=k, replace=False)
        z = np.zeros(d, dtype=np.float32)
        z[idx] = np.random.normal(0.0, sigma, size=k)
        out.append(clip_bounds(elite + z, W))

    # Deduplicate at 1e-3
    seen = set()
    deduped = []
    for g in out:
        key = tuple(np.round(g, 3))
        if key in seen:
            repl = np.random.uniform(-W, W, size=d)
            deduped.append(repl)
            seen.add(tuple(np.round(repl, 3)))
        else:
            deduped.append(g)
            seen.add(key)

    deduped = deduped[:popsize]
    while len(deduped) < popsize:
        deduped.append(np.random.uniform(-W, W, size=d))
    return deduped

# Save best genome 
def save_best_genome(path: Path, genome: np.ndarray, popsize: int, generations: int, best_gen_index: int) -> None:
    out = {
        "genome": np.asarray(genome, dtype=np.float32).tolist(),
        "POPULATION_SIZE": int(popsize),
        "GENERATIONS": int(generations),
        "BEST_OVERALL_FROM_GENERATION": int(best_gen_index),
    }
    with path.open("w") as f:
        json.dump(out, f, indent=2)


# Save generation data including paths and fitness
def save_generation_data(path: Path, generation_data: dict) -> None:
    """Save comprehensive data for all generations including robot paths and fitness."""
    # Convert numpy arrays to lists for JSON serialization
    serializable_data = {}
    for gen, data in generation_data.items():
        serializable_data[str(gen)] = {
            "best_genome": data["best_genome"].tolist() if data["best_genome"] is not None else None,
            "best_fitness": float(data["best_fitness"]),
            "fitness_components": {k: float(v) for k, v in data["fitness_components"].items()},
            "robot_paths": {
                terrain: [pos.tolist() for pos in path] if path is not None else None
                for terrain, path in data["robot_paths"].items()
            } if data["robot_paths"] is not None else None
        }
    
    with path.open("w") as f:
        json.dump(serializable_data, f, indent=2)


# Create path visualization plots
def plot_robot_paths(generation_data: dict, save_dir: Path, generations_to_plot=None):
    """Create visualizations of robot paths across generations and terrains."""
    if generations_to_plot is None:
        # Plot first, middle, and last generations, plus any significant improvements
        max_gen = max(generation_data.keys())
        generations_to_plot = [0, max_gen // 4, max_gen // 2, 3 * max_gen // 4, max_gen]
        generations_to_plot = [g for g in generations_to_plot if g in generation_data]
    
    # Create subplots for each terrain
    fig, axes = plt.subplots(1, len(TERRAIN_SPAWNS), figsize=(15, 5))
    if len(TERRAIN_SPAWNS) == 1:
        axes = [axes]
    
    colors = plt.cm.viridis(np.linspace(0, 1, len(generations_to_plot)))
    
    for terrain_idx, (terrain_name, spawn_pos) in enumerate(TERRAIN_SPAWNS):
        ax = axes[terrain_idx]
        
        for gen_idx, gen in enumerate(generations_to_plot):
            if gen in generation_data and generation_data[gen]["robot_paths"] is not None:
                path = generation_data[gen]["robot_paths"].get(terrain_name)
                if path is not None:
                    path_array = np.array(path)
                    fitness = generation_data[gen]["fitness_components"].get(terrain_name, 0)
                    ax.plot(path_array[:, 0], path_array[:, 1], 
                           color=colors[gen_idx], linewidth=2, alpha=0.8,
                           label=f'Gen {gen} (fit={fitness:.2f})')
                    
                    # Mark start and end points
                    ax.scatter(path_array[0, 0], path_array[0, 1], 
                              color=colors[gen_idx], marker='o', s=100, alpha=0.8)
                    ax.scatter(path_array[-1, 0], path_array[-1, 1], 
                              color=colors[gen_idx], marker='s', s=100, alpha=0.8)
        
        # Mark spawn position and target
        ax.scatter(spawn_pos[0], spawn_pos[1], color='red', marker='*', s=200, 
                  label='Spawn', zorder=10)
        ax.scatter(TARGET[0], TARGET[1], color='gold', marker='*', s=200, 
                  label='Target', zorder=10)
        
        ax.set_xlabel('X Position')
        ax.set_ylabel('Y Position')
        ax.set_title(f'{terrain_name.capitalize()} Terrain')
        ax.grid(True, alpha=0.3)
        ax.legend(loc='best', fontsize=8)
        ax.set_aspect('equal', adjustable='box')
    
    plt.tight_layout()
    path_plot_filename = f"robot_paths_evolution_3terrains.png"
    path_plot_path = save_dir / path_plot_filename
    plt.savefig(path_plot_path, dpi=160, bbox_inches='tight')
    print(f" Saved path visualization: {path_plot_path}")
    plt.close()


def main():
    # Load body graph and elite 
    with ELITE_BRAIN_JSON.open("r") as f:
        elite_data = json.load(f)
    elite = np.array(elite_data["genome"], dtype=np.float32)

    assert elite.size == GENOME_SIZE, (
        f"Elite genome length {elite.size} != expected {GENOME_SIZE}. "
        f"(Check INPUT_SIZE/HIDDEN_SIZE/OUTPUT_SIZE or the saved genome.)"
    )

    # initialize generation 0 for a population
    gen0 = make_gen0_population(elite, POPULATION_SIZE, INITIAL_WEIGHT_RANGE)

    best_overall = {
        "genome": elite.copy(),
        "total": -np.inf,
        "comps": {name: 0.0 for name, _ in TERRAIN_SPAWNS},
        "gen": -1,
    }

    # Initialize generation data storage
    generation_data = {}
    
    # print("\n[Gen 0] Evaluating custom populatiuon")  # Commented out: superfluous
    total_scores_g0 = []
    best_total_g0 = -np.inf
    best_comps_g0 = {}
    best_genome_g0 = None
    best_paths_g0 = None

    # Add progress tracking for generation 0 evaluation
    for i, cand in track(enumerate(gen0), description="[Gen 0] Evaluating initial population", total=len(gen0)):
        tot, comps = evaluate_multi_terrain(cand, SIMULATION_STEPS)
        total_scores_g0.append(tot)
        if tot > best_total_g0:
            best_total_g0 = tot
            best_comps_g0 = comps
            best_genome_g0 = cand.copy()
        if tot > best_overall["total"]:
            best_overall.update({"genome": cand.copy(), "total": tot, "comps": comps, "gen": 0})

    # Record best robot path for generation 0
    if best_genome_g0 is not None:
        _, _, best_paths_g0 = evaluate_multi_terrain(best_genome_g0, SIMULATION_STEPS, record_paths=True)
    
    # Store generation 0 data
    generation_data[0] = {
        "best_genome": best_genome_g0,
        "best_fitness": best_total_g0,
        "fitness_components": best_comps_g0,
        "robot_paths": best_paths_g0
    }

    print(f"[Gen 0] Best total={best_total_g0:.3f}, comps={ {k: round(v, 3) for k, v in best_comps_g0.items()} }")

    # EvoTorch Problem 
    problem = Problem(
        "max",
        evotorch_eval,
        solution_length=int(GENOME_SIZE),
        dtype=torch.float32,
        initial_bounds=(-INITIAL_WEIGHT_RANGE, INITIAL_WEIGHT_RANGE),
    )

    # ERROR REPLACEMENT
    # problem = Problem(
    #     objective_sense="max",
    #     objective=evotorch_eval,
    #     solution_length=int(GENOME_SIZE),
    #     dtype=torch.float32,
    #     initial_bounds=(-INITIAL_WEIGHT_RANGE, INITIAL_WEIGHT_RANGE),
    # )

    # CMA-ES 
    searcher = CMAES(
        problem,
        popsize=POPULATION_SIZE,
        stdev_init=0.5,
    )

    fitness_history = [best_total_g0]
    per_terrain_history = {name: [best_comps_g0.get(name, 0.0)] for name, _ in TERRAIN_SPAWNS}

    # Create a rich progress bar for the main evolution loop
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TimeElapsedColumn(),
        TimeRemainingColumn(),
        console=None,  # Use default console
    ) as progress:
        evolution_task = progress.add_task("[green]Evolving brains...", total=GENERATIONS)
        
        for gen in range(1, GENERATIONS + 1):
            searcher.step()

            #best-of-gen with per-terrain
            gen_best_total = -np.inf
            gen_best_comps = {}
            gen_best_genome = None

            # Add nested progress bar for population evaluation
            pop_task = progress.add_task(f"[blue]Gen {gen} evaluation", total=len(searcher.population))
            
            for sol in searcher.population:
                g = sol.values.detach().cpu().numpy().astype(np.float32)
                tot, comps = evaluate_multi_terrain(g, SIMULATION_STEPS)
                if tot > gen_best_total:
                    gen_best_total = tot
                    gen_best_comps = comps
                    gen_best_genome = g
                progress.advance(pop_task)

            progress.remove_task(pop_task)  # Clean up nested task

            # Record best robot path for this generation
            gen_best_paths = None
            if gen_best_genome is not None:
                _, _, gen_best_paths = evaluate_multi_terrain(gen_best_genome, SIMULATION_STEPS, record_paths=True)
            
            # Store generation data
            generation_data[gen] = {
                "best_genome": gen_best_genome.copy() if gen_best_genome is not None else None,
                "best_fitness": gen_best_total,
                "fitness_components": gen_best_comps.copy(),
                "robot_paths": gen_best_paths
            }

            fitness_history.append(gen_best_total)
            for name, _ in TERRAIN_SPAWNS:
                per_terrain_history[name].append(gen_best_comps.get(name, 0.0))

            if gen_best_total > best_overall["total"]:
                best_overall.update({"genome": gen_best_genome.copy(), "total": gen_best_total, "comps": gen_best_comps, "gen": gen})
                print(f"New BEST gen:{gen}, total={gen_best_total:.3f}")  # Keep important updates
            
            # Update main progress bar with current best info
            progress.update(evolution_task, description=f"[green]Evolving brains... Best: {best_overall['total']:.3f}")
            progress.advance(evolution_task)

    # Save best genome
    save_dir = Path(r"ImprovementRuns/MultiTerrain")
    save_dir.mkdir(parents=True, exist_ok=True)

    json_filename = f"best_genome_POP{POPULATION_SIZE}_GEN{GENERATIONS}_3terrains.json"
    json_path = save_dir / json_filename

    save_best_genome(json_path, best_overall["genome"], POPULATION_SIZE, GENERATIONS, int(best_overall["gen"]))
    print(f"\n[RESULT] Best total={best_overall['total']:.3f} from generation {best_overall['gen']}")
    print(f" Per-terrain: { {k: round(v,3) for k, v in best_overall['comps'].items()} }")
    print(f" Saved best genome: {json_path}")

    # Save comprehensive generation data (including robot paths and fitness for all generations)
    generation_data_filename = f"generation_data_POP{POPULATION_SIZE}_GEN{GENERATIONS}_3terrains.json"
    generation_data_path = save_dir / generation_data_filename
    save_generation_data(generation_data_path, generation_data)
    print(f" Saved generation data: {generation_data_path}")

    # Create robot path visualizations
    plot_robot_paths(generation_data, save_dir)

    # Plot fitness progress
    plt.figure(figsize=(8, 5))
    plt.plot(fitness_history, marker="o", linestyle="-", label="Total (best-of-gen)")
    for name, series in per_terrain_history.items():
        plt.plot(series, linestyle="--", label=name)
    plt.xlabel("Generation")
    plt.ylabel("Fitness (sum of projected progress)")
    plt.title("Evolution Progress (CMA-ES) — Brain Only, 3 Terrains")
    plt.grid(True)
    plt.legend()
    plot_path = save_dir / "fitness_progress_3terrains.png"
    plt.savefig(plot_path, dpi=160)
    print(f" Saved plot: {plot_path}")


if __name__ == "__main__":
    main()

