# Brain improvement on 3 Terrains (CMA-ES)
# takes Step_Curry brain and body. 
# population is generated by placing step curry and:
    # a gaussian around the elite.
    #  immigrants (rando)
    # some sparse

# Third-party libraries
import numpy as np
import torch
import json
from pathlib import Path
from evotorch import Problem
from evotorch.algorithms import CMAES
import matplotlib.pyplot as plt
import networkx as nx
import mujoco
from mujoco import mj_step, viewer
from rich.progress import track, Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn, TimeRemainingColumn
import scipy.cluster.hierarchy
import scipy.spatial.distance

# ariel imports
from ariel.simulation.environments.olympic_arena import OlympicArena
from ariel.body_phenotypes.robogen_lite.modules.core import CoreModule
from ariel.body_phenotypes.robogen_lite.modules.brick import BrickModule
from ariel.body_phenotypes.robogen_lite.modules.hinge import HingeModule
from ariel.body_phenotypes.robogen_lite.config import ModuleFaces

# Settings 
JSON_PATH = Path(r"Robot_Result/Step_Curry.json") # BODY stays fixed
ELITE_BRAIN_JSON = Path(r"Robot_Result/Step_Curry_Brain.json")
POPULATION_SIZE = 50
GENERATIONS = 150
SIMULATION_STEPS = 7500
INITIAL_WEIGHT_RANGE = 1.0
HIDDEN_SIZE = 16
MAX_VELOCITY = 0.05
MAX_ANGLE = np.pi / 2
TIME_INPUTS = 2
position = [-0.8, 0, 0.1]  # kept for compatibility (not used directly for multi-terrain)
TARGET_POSITION = [5.0, 0.0, 0.5]  # Target to reach

#terrain spawns 
SPAWN_FLAT   = np.array([-2.40, 0.0, 0.10], dtype=np.float64)
SPAWN_RUGGED = np.array([-0.90, 0.0, 0.12], dtype=np.float64)
SPAWN_HILL   = np.array([ 2.65, 0.0, 0.12], dtype=np.float64)
TERRAIN_SPAWNS = (
    ("flat",   SPAWN_FLAT),
    ("rugged", SPAWN_RUGGED),
    ("hill",   SPAWN_HILL),
)

# Gen-0 population:
# elite + Gaussian around elite + immigrants + sparse
P_LOCAL = 0.60
P_IMM = 0.30
P_SPARSE = 0.10
SIGMA_LOCAL = 0.25 # fraction of INITIAL_WEIGHT_RANGE
SPARSE_FRAC = 0.15 # fraction of coordinates perturbed


# Helpers: JSON graph loader and robot constructor 
def load_graph_from_json(path: Path) -> nx.DiGraph:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    graph = nx.DiGraph()
    for node in data["nodes"]:
        graph.add_node(node["id"], type=node["type"], rotation=node.get("rotation", "DEG_0"))
    for edge in data["edges"]:
        graph.add_edge(edge["source"], edge["target"], face=edge["face"])
    return graph


def construct_core_from_graph(graph: nx.DiGraph):
    modules = {}
    for node_id, attrs in graph.nodes(data=True):
        node_type = attrs["type"]
        rotation = attrs.get("rotation", "DEG_0")
        if node_type == "CORE":
            modules[node_id] = CoreModule(index=node_id)
        elif node_type == "BRICK":
            modules[node_id] = BrickModule(index=node_id)
        elif node_type == "HINGE":
            modules[node_id] = HingeModule(index=node_id)
        else:
            modules[node_id] = None
        if node_type in ["HINGE", "BRICK"] and modules[node_id] is not None:
            try:
                deg = int(rotation.replace("DEG_", ""))
                modules[node_id].rotate(deg)
            except Exception:
                pass
    # attach bodies according to edges
    for src, tgt, edge_attrs in graph.edges(data=True):
        face = edge_attrs["face"]
        src_module = modules.get(src)
        tgt_module = modules.get(tgt)
        if src_module is None or tgt_module is None:
            continue
        try:
            src_module.sites[getattr(ModuleFaces, face)].attach_body(
                body=tgt_module.body,
                prefix=f"{tgt_module.__class__.__name__.lower()}_{tgt}"
            )
        except Exception:
            pass
    core_nodes = [nid for nid, attrs in graph.nodes(data=True) if attrs["type"] == "CORE"]
    if len(core_nodes) != 1:
        raise ValueError("Expected exactly one CORE module")
    return modules[core_nodes[0]], modules


# Decode genome 
def tanh(x):
    return np.tanh(x)


def normalize_qpos(qpos: np.ndarray) -> np.ndarray:
    # qpos are angles/positions; for angles normalise by pi to [-1,1]
    return np.clip(qpos / np.pi, -1.0, 1.0)


def normalize_xpos(xpos_flat: np.ndarray) -> np.ndarray:
    return np.clip(xpos_flat / 10.0, -1.0, 1.0)


def normalize_xmat(xmat_flat: np.ndarray) -> np.ndarray:
    return np.clip(xmat_flat, -1.0, 1.0)


def assemble_inputs_from_data(data, model):
    """
    COPY of your feature assembly but limited to core (as in your latest files):
    - qpos (NQ)
    - core xpos (3)
    - core xmat flattened (9)
    - time features added by caller
    """
    NQ = model.nq
    # qpos
    qpos = np.array(data.qpos[:NQ], dtype=np.float64)
    qpos_norm = normalize_qpos(qpos)
    # core body position
    try:
        xpos = np.array(data.xpos[0], dtype=np.float64)
    except Exception:
        xpos = np.zeros(3, dtype=np.float64)
    xpos_norm = normalize_xpos(xpos)
    # core body rotation matrix
    try:
        xmat = np.array(data.xmat[0].reshape(-1), dtype=np.float64)
    except Exception:
        xmat = np.zeros(9, dtype=np.float64)
    xmat_norm = normalize_xmat(xmat)
    features = np.concatenate([qpos_norm, xpos_norm, xmat_norm]).astype(np.float32)
    return features


def velocity_to_target(prev_ctrl: np.ndarray, raw_outputs: np.ndarray) -> np.ndarray:
    velocity = raw_outputs * MAX_VELOCITY
    new_ctrl = prev_ctrl + velocity
    return np.clip(new_ctrl, -MAX_ANGLE, MAX_ANGLE)


def decode_genome(genome, input_size, output_size):
    g = np.array(genome, dtype=np.float64)
    idx = 0
    W_in = g[idx: idx + input_size * HIDDEN_SIZE].reshape(input_size, HIDDEN_SIZE)
    idx += input_size * HIDDEN_SIZE
    W_rec = g[idx: idx + HIDDEN_SIZE * HIDDEN_SIZE].reshape(HIDDEN_SIZE, HIDDEN_SIZE)
    idx += HIDDEN_SIZE * HIDDEN_SIZE
    W_out = g[idx: idx + HIDDEN_SIZE * output_size].reshape(HIDDEN_SIZE, output_size)
    return W_in, W_rec, W_out


# Build sample model to determine sizes
robot_graph = load_graph_from_json(JSON_PATH)
core_for_dims, _ = construct_core_from_graph(robot_graph)
world_for_dims = OlympicArena()
world_for_dims.spawn(core_for_dims.spec, position=np.array(SPAWN_FLAT))  # NOTE: spawn_position

#ERROR POSITION
# world_for_dims.spawn(core_for_dims.spec, position=np.array(SPAWN_FLAT))

model_for_dims = world_for_dims.spec.compile()

NQ = int(model_for_dims.nq)
NU = int(model_for_dims.nu)
BASE_INPUT_SIZE = NQ + 3 + 9
INPUT_SIZE = BASE_INPUT_SIZE + TIME_INPUTS
OUTPUT_SIZE = NU
GENOME_SIZE = INPUT_SIZE * HIDDEN_SIZE + HIDDEN_SIZE * HIDDEN_SIZE + HIDDEN_SIZE * OUTPUT_SIZE


# target on terrains 
TARGET = np.array(TARGET_POSITION, dtype=np.float64)

def episode_progress(genome: np.ndarray, spawn_xyz: np.ndarray, steps: int, record_path=False) -> tuple:
    core, _ = construct_core_from_graph(robot_graph)
    world = OlympicArena()
    world.spawn(core.spec, position=np.array(spawn_xyz))

    #ERROR POSITION
    # world.spawn(core.spec, position=np.array(spawn_xyz))

    model = world.spec.compile()
    data = mujoco.MjData(model)

    mujoco.mj_resetData(model, data)
    data.qvel[:] = 0
    data.qacc[:] = 0
    mujoco.mj_forward(model, data)

    # unit direction from spawn to target
    spawn_vec = np.array(spawn_xyz, dtype=np.float64)
    dir_vec = TARGET - spawn_vec
    n = np.linalg.norm(dir_vec)
    u_dir = dir_vec / n if n > 1e-9 else np.array([1.0, 0.0, 0.0])

    W_in, W_rec, W_out = decode_genome(genome, INPUT_SIZE, OUTPUT_SIZE)
    h = np.zeros(HIDDEN_SIZE, dtype=np.float64)
    ctrl_state = np.zeros(OUTPUT_SIZE, dtype=np.float64)

    best_proj = 0.0
    path = [] if record_path else None

    for t in range(steps):
        base_feats = assemble_inputs_from_data(data, model)
        phase = 2 * np.pi * (t / steps)
        time_feats = np.array([np.sin(phase), np.cos(phase)], dtype=np.float32)
        inputs = np.concatenate([base_feats, time_feats]).astype(np.float64)

        h = tanh(np.dot(inputs, W_in) + np.dot(h, W_rec))
        raw_outputs = tanh(np.dot(h, W_out))
        ctrl_state = velocity_to_target(ctrl_state, raw_outputs)
        napply = min(len(data.ctrl), len(ctrl_state))
        data.ctrl[:napply] = ctrl_state[:napply]

        mj_step(model, data)

        try:
            p = np.array(data.xpos[0], dtype=np.float64)
        except Exception:
            p = spawn_vec
        
        # Record path if requested
        if record_path:
            path.append(p.copy())
            
        proj = float(np.dot(p - spawn_vec, u_dir))
        if proj > best_proj:
            best_proj = proj

    fitness = max(0.0, best_proj)
    if record_path:
        return fitness, path
    else:
        return fitness, None


# 3-terrain fitness wrapper
def evaluate_multi_terrain(genome: np.ndarray, steps: int, record_paths=False):
    comps = {}
    paths = {} if record_paths else None
    total = 0.0
    for name, spawn in TERRAIN_SPAWNS:
        fitness, path = episode_progress(genome, spawn, steps, record_path=record_paths)
        comps[name] = fitness
        if record_paths:
            paths[name] = path
        total += fitness
    if record_paths:
        return total, comps, paths
    else:
        return total, comps


# Evaluate wrapper for EvoTorch 
def evotorch_eval(genome: torch.Tensor) -> float:
    g = genome.detach().cpu().numpy().astype(np.float32)
    result = evaluate_multi_terrain(g, SIMULATION_STEPS)
    tot = result[0]  # First element is always total fitness
    return float(tot)


def clip_bounds(x: np.ndarray, W: float) -> np.ndarray:
    return np.clip(x, -W, W)


def make_gen0_population(elite: np.ndarray, popsize: int, W: float):
    out = [elite.copy()]  # slot 0 = elite
    d = elite.size

    n_local = int(P_LOCAL * popsize)
    n_imm = int(P_IMM * popsize)
    n_sparse = int(P_SPARSE * popsize)

    used = 1 + n_local + n_imm + n_sparse
    if used > popsize:
        overflow = used - popsize
        n_sparse = max(0, n_sparse - overflow)
    elif used < popsize:
        n_local += (popsize - used)

    sigma = SIGMA_LOCAL * W

    # Local Gaussian
    for _ in range(n_local):
        z = np.random.normal(0.0, sigma, size=d)
        out.append(clip_bounds(elite + z, W))

    # Immigrants (uniform)
    for _ in range(n_imm):
        out.append(np.random.uniform(-W, W, size=d))

    # Sparse perturbations
    k = max(1, int(SPARSE_FRAC * d))
    for _ in range(n_sparse):
        idx = np.random.choice(d, size=k, replace=False)
        z = np.zeros(d, dtype=np.float32)
        z[idx] = np.random.normal(0.0, sigma, size=k)
        out.append(clip_bounds(elite + z, W))

    # Deduplicate at 1e-3
    seen = set()
    deduped = []
    for g in out:
        key = tuple(np.round(g, 3))
        if key in seen:
            repl = np.random.uniform(-W, W, size=d)
            deduped.append(repl)
            seen.add(tuple(np.round(repl, 3)))
        else:
            deduped.append(g)
            seen.add(key)

    deduped = deduped[:popsize]
    while len(deduped) < popsize:
        deduped.append(np.random.uniform(-W, W, size=d))
    return deduped

# Save best genome 
def save_best_genome(path: Path, genome: np.ndarray, popsize: int, generations: int, best_gen_index: int) -> None:
    out = {
        "genome": np.asarray(genome, dtype=np.float32).tolist(),
        "POPULATION_SIZE": int(popsize),
        "GENERATIONS": int(generations),
        "BEST_OVERALL_FROM_GENERATION": int(best_gen_index),
    }
    with path.open("w") as f:
        json.dump(out, f, indent=2)


# Save generation data including paths and fitness
def save_generation_data(path: Path, generation_data: dict) -> None:
    """Save comprehensive data for all generations including robot paths and fitness."""
    # Convert numpy arrays to lists for JSON serialization
    serializable_data = {}
    for gen, data in generation_data.items():
        serializable_data[str(gen)] = {
            "best_genome": data["best_genome"].tolist() if data["best_genome"] is not None else None,
            "best_fitness": float(data["best_fitness"]),
            "fitness_components": {k: float(v) for k, v in data["fitness_components"].items()},
            "robot_paths": {
                terrain: [pos.tolist() for pos in path] if path is not None else None
                for terrain, path in data["robot_paths"].items()
            } if data["robot_paths"] is not None else None,
            "network_analysis": data.get("network_analysis", None)
        }
    
    with path.open("w") as f:
        json.dump(serializable_data, f, indent=2)


# Analyze neural network structure for regularity and motif reuse
def analyze_network_structure(genome: np.ndarray, input_size: int, output_size: int) -> dict:
    """Analyze neural network weights for structural patterns, regularity, and motif reuse."""
    W_in, W_rec, W_out = decode_genome(genome, input_size, output_size)
    
    analysis = {}
    
    # 1. Weight distribution analysis
    all_weights = np.concatenate([W_in.flatten(), W_rec.flatten(), W_out.flatten()])
    analysis["weight_statistics"] = {
        "mean": float(np.mean(all_weights)),
        "std": float(np.std(all_weights)),
        "min": float(np.min(all_weights)),
        "max": float(np.max(all_weights)),
        "sparsity": float(np.sum(np.abs(all_weights) < 0.01) / len(all_weights))
    }
    
    # 2. Regularity measures - look for repeated patterns
    def find_repeated_patterns(matrix, pattern_size=3):
        """Find repeated weight patterns in a matrix."""
        patterns = {}
        rows, cols = matrix.shape
        for i in range(rows - pattern_size + 1):
            for j in range(cols - pattern_size + 1):
                pattern = matrix[i:i+pattern_size, j:j+pattern_size]
                pattern_key = tuple(np.round(pattern.flatten(), 3))
                if pattern_key in patterns:
                    patterns[pattern_key] += 1
                else:
                    patterns[pattern_key] = 1
        return patterns
    
    # Analyze each weight matrix for repeated patterns
    input_patterns = find_repeated_patterns(W_in)
    recurrent_patterns = find_repeated_patterns(W_rec)
    output_patterns = find_repeated_patterns(W_out)
    
    analysis["pattern_reuse"] = {
        "input_layer_repeated_patterns": len([count for count in input_patterns.values() if count > 1]),
        "recurrent_layer_repeated_patterns": len([count for count in recurrent_patterns.values() if count > 1]),
        "output_layer_repeated_patterns": len([count for count in output_patterns.values() if count > 1]),
        "total_repeated_patterns": len([count for count in input_patterns.values() if count > 1]) + 
                                 len([count for count in recurrent_patterns.values() if count > 1]) + 
                                 len([count for count in output_patterns.values() if count > 1])
    }
    
    # 3. Symmetry and regularity measures
    def compute_symmetry_score(matrix):
        """Compute how symmetric a matrix is."""
        if matrix.shape[0] != matrix.shape[1]:
            return 0.0
        return float(1.0 - np.mean(np.abs(matrix - matrix.T)) / np.mean(np.abs(matrix)))
    
    analysis["structural_regularity"] = {
        "recurrent_symmetry": compute_symmetry_score(W_rec),
        "input_column_similarity": float(np.mean([np.corrcoef(W_in[:, i], W_in[:, j])[0, 1] 
                                                for i in range(W_in.shape[1]) 
                                                for j in range(i+1, W_in.shape[1]) 
                                                if not np.isnan(np.corrcoef(W_in[:, i], W_in[:, j])[0, 1])])),
        "output_row_similarity": float(np.mean([np.corrcoef(W_out[i, :], W_out[j, :])[0, 1] 
                                              for i in range(W_out.shape[0]) 
                                              for j in range(i+1, W_out.shape[0])
                                              if not np.isnan(np.corrcoef(W_out[i, :], W_out[j, :])[0, 1])]))
    }
    
    # 4. Functional modularity - cluster analysis of weights
    from scipy.cluster.hierarchy import linkage, fcluster
    from scipy.spatial.distance import pdist
    
    try:
        # Cluster hidden units based on their recurrent connections
        if W_rec.shape[0] > 3:  # Need at least 4 units for meaningful clustering
            distances = pdist(W_rec, metric='euclidean')
            linkage_matrix = linkage(distances, method='ward')
            clusters = fcluster(linkage_matrix, t=max(2, W_rec.shape[0]//4), criterion='maxclust')
            
            # Measure modularity - how well-separated are the clusters
            n_clusters = len(np.unique(clusters))
            within_cluster_var = 0
            between_cluster_var = 0
            
            for cluster_id in np.unique(clusters):
                cluster_mask = clusters == cluster_id
                cluster_weights = W_rec[cluster_mask][:, cluster_mask]
                within_cluster_var += np.var(cluster_weights)
                
                other_mask = clusters != cluster_id
                if np.sum(other_mask) > 0:
                    between_weights = W_rec[cluster_mask][:, other_mask]
                    between_cluster_var += np.var(between_weights)
            
            modularity_score = between_cluster_var / (within_cluster_var + 1e-8)
            
            analysis["functional_modularity"] = {
                "num_clusters": int(n_clusters),
                "modularity_score": float(modularity_score),
                "cluster_sizes": [int(np.sum(clusters == i)) for i in np.unique(clusters)]
            }
    except:
        analysis["functional_modularity"] = {
            "num_clusters": 1,
            "modularity_score": 0.0,
            "cluster_sizes": [HIDDEN_SIZE]
        }
    
    # 5. Efficiency measures
    effective_connections = np.sum(np.abs(all_weights) > 0.01)
    total_connections = len(all_weights)
    
    analysis["efficiency_metrics"] = {
        "connection_efficiency": float(effective_connections / total_connections),
        "weight_magnitude_distribution": {
            "small_weights_pct": float(np.sum(np.abs(all_weights) < 0.1) / len(all_weights)),
            "medium_weights_pct": float(np.sum((np.abs(all_weights) >= 0.1) & (np.abs(all_weights) < 0.5)) / len(all_weights)),
            "large_weights_pct": float(np.sum(np.abs(all_weights) >= 0.5) / len(all_weights))
        }
    }
    
    return analysis


# Create path visualization plots
def plot_robot_paths(generation_data: dict, save_dir: Path, generations_to_plot=None):
    """Create visualizations of robot paths across generations and terrains."""
    if generations_to_plot is None:
        # Plot first, middle, and last generations, plus any significant improvements
        max_gen = max(generation_data.keys())
        generations_to_plot = [0, max_gen // 4, max_gen // 2, 3 * max_gen // 4, max_gen]
        generations_to_plot = [g for g in generations_to_plot if g in generation_data]
    
    # Create subplots for each terrain
    fig, axes = plt.subplots(1, len(TERRAIN_SPAWNS), figsize=(15, 5))
    if len(TERRAIN_SPAWNS) == 1:
        axes = [axes]
    
    colors = plt.cm.viridis(np.linspace(0, 1, len(generations_to_plot)))
    
    for terrain_idx, (terrain_name, spawn_pos) in enumerate(TERRAIN_SPAWNS):
        ax = axes[terrain_idx]
        
        for gen_idx, gen in enumerate(generations_to_plot):
            if gen in generation_data and generation_data[gen]["robot_paths"] is not None:
                path = generation_data[gen]["robot_paths"].get(terrain_name)
                if path is not None:
                    path_array = np.array(path)
                    fitness = generation_data[gen]["fitness_components"].get(terrain_name, 0)
                    ax.plot(path_array[:, 0], path_array[:, 1], 
                           color=colors[gen_idx], linewidth=2, alpha=0.8,
                           label=f'Gen {gen} (fit={fitness:.2f})')
                    
                    # Mark start and end points
                    ax.scatter(path_array[0, 0], path_array[0, 1], 
                              color=colors[gen_idx], marker='o', s=100, alpha=0.8)
                    ax.scatter(path_array[-1, 0], path_array[-1, 1], 
                              color=colors[gen_idx], marker='s', s=100, alpha=0.8)
        
        # Mark spawn position and target
        ax.scatter(spawn_pos[0], spawn_pos[1], color='red', marker='*', s=200, 
                  label='Spawn', zorder=10)
        ax.scatter(TARGET[0], TARGET[1], color='gold', marker='*', s=200, 
                  label='Target', zorder=10)
        
        ax.set_xlabel('X Position')
        ax.set_ylabel('Y Position')
        ax.set_title(f'{terrain_name.capitalize()} Terrain')
        ax.grid(True, alpha=0.3)
        ax.legend(loc='best', fontsize=8)
        ax.set_aspect('equal', adjustable='box')
    
    plt.tight_layout()
    path_plot_filename = f"robot_paths_evolution_3terrains_shania.png"
    path_plot_path = save_dir / path_plot_filename
    plt.savefig(path_plot_path, dpi=160, bbox_inches='tight')
    print(f" Saved path visualization: {path_plot_path}")
    plt.close()


# Analyze evolution of network structure patterns
def analyze_structural_evolution(generation_data: dict, save_dir: Path):
    """Analyze how network structural patterns evolve over generations."""
    generations = sorted([gen for gen in generation_data.keys() if generation_data[gen]["network_analysis"] is not None])
    
    if len(generations) == 0:
        print("No network analysis data available for structural evolution analysis")
        return
    
    # Extract metrics over generations
    metrics = {
        'fitness': [],
        'pattern_reuse': [],
        'modularity': [],
        'symmetry': [],
        'efficiency': [],
        'sparsity': []
    }
    
    for gen in generations:
        analysis = generation_data[gen]["network_analysis"]
        metrics['fitness'].append(generation_data[gen]["best_fitness"])
        metrics['pattern_reuse'].append(analysis["pattern_reuse"]["total_repeated_patterns"])
        metrics['modularity'].append(analysis["functional_modularity"]["modularity_score"])
        metrics['symmetry'].append(analysis["structural_regularity"]["recurrent_symmetry"])
        metrics['efficiency'].append(analysis["efficiency_metrics"]["connection_efficiency"])
        metrics['sparsity'].append(analysis["weight_statistics"]["sparsity"])
    
    # Create comprehensive analysis plots
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    fig.suptitle('Evolution of Neural Network Structural Properties\n(Evidence for/against Generative Encoding Hypothesis)', fontsize=16)
    
    # Plot 1: Fitness vs Pattern Reuse
    axes[0, 0].scatter(metrics['pattern_reuse'], metrics['fitness'], alpha=0.7, c=generations, cmap='viridis')
    axes[0, 0].set_xlabel('Number of Repeated Patterns')
    axes[0, 0].set_ylabel('Fitness')
    axes[0, 0].set_title('Fitness vs Pattern Reuse\n(Higher reuse supports hypothesis)')
    axes[0, 0].grid(True, alpha=0.3)
    
    # Add correlation coefficient
    if len(metrics['pattern_reuse']) > 2:
        corr_coef = np.corrcoef(metrics['pattern_reuse'], metrics['fitness'])[0, 1]
        axes[0, 0].text(0.05, 0.95, f'r = {corr_coef:.3f}', transform=axes[0, 0].transAxes, 
                       bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))
    
    # Plot 2: Evolution of Modularity over Generations
    axes[0, 1].plot(generations, metrics['modularity'], 'bo-', alpha=0.7)
    axes[0, 1].set_xlabel('Generation')
    axes[0, 1].set_ylabel('Modularity Score')
    axes[0, 1].set_title('Functional Modularity Evolution\n(Increasing trend supports hypothesis)')
    axes[0, 1].grid(True, alpha=0.3)
    
    # Plot 3: Efficiency vs Fitness
    axes[0, 2].scatter(metrics['efficiency'], metrics['fitness'], alpha=0.7, c=generations, cmap='viridis')
    axes[0, 2].set_xlabel('Connection Efficiency')
    axes[0, 2].set_ylabel('Fitness')
    axes[0, 2].set_title('Efficiency vs Fitness\n(Positive correlation supports hypothesis)')
    axes[0, 2].grid(True, alpha=0.3)
    
    if len(metrics['efficiency']) > 2:
        corr_coef = np.corrcoef(metrics['efficiency'], metrics['fitness'])[0, 1]
        axes[0, 2].text(0.05, 0.95, f'r = {corr_coef:.3f}', transform=axes[0, 2].transAxes,
                       bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))
    
    # Plot 4: Sparsity Evolution
    axes[1, 0].plot(generations, metrics['sparsity'], 'ro-', alpha=0.7)
    axes[1, 0].set_xlabel('Generation')
    axes[1, 0].set_ylabel('Network Sparsity')
    axes[1, 0].set_title('Network Sparsity Evolution\n(Increasing sparsity supports efficiency)')
    axes[1, 0].grid(True, alpha=0.3)
    
    # Plot 5: Symmetry Evolution
    axes[1, 1].plot(generations, metrics['symmetry'], 'go-', alpha=0.7)
    axes[1, 1].set_xlabel('Generation')
    axes[1, 1].set_ylabel('Recurrent Symmetry')
    axes[1, 1].set_title('Structural Symmetry Evolution\n(Regularity indicator)')
    axes[1, 1].grid(True, alpha=0.3)
    
    # Plot 6: Multi-metric correlation heatmap
    import matplotlib.cm as cm
    metric_names = ['Fitness', 'Pattern Reuse', 'Modularity', 'Symmetry', 'Efficiency', 'Sparsity']
    metric_values = np.array([metrics['fitness'], metrics['pattern_reuse'], metrics['modularity'], 
                             metrics['symmetry'], metrics['efficiency'], metrics['sparsity']])
    
    if metric_values.shape[1] > 2:  # Need at least 3 data points for meaningful correlation
        correlation_matrix = np.corrcoef(metric_values)
        correlation_matrix = np.nan_to_num(correlation_matrix)  # Replace NaN with 0
        
        im = axes[1, 2].imshow(correlation_matrix, cmap='RdBu_r', vmin=-1, vmax=1)
        axes[1, 2].set_xticks(range(len(metric_names)))
        axes[1, 2].set_yticks(range(len(metric_names)))
        axes[1, 2].set_xticklabels(metric_names, rotation=45, ha='right')
        axes[1, 2].set_yticklabels(metric_names)
        axes[1, 2].set_title('Metric Correlations\n(Structure-Performance Links)')
        
        # Add correlation values to heatmap
        for i in range(len(metric_names)):
            for j in range(len(metric_names)):
                text = axes[1, 2].text(j, i, f'{correlation_matrix[i, j]:.2f}',
                                     ha="center", va="center", color="black" if abs(correlation_matrix[i, j]) < 0.5 else "white")
        
        plt.colorbar(im, ax=axes[1, 2], shrink=0.6)
    else:
        axes[1, 2].text(0.5, 0.5, 'Insufficient data\nfor correlation analysis', 
                       ha='center', va='center', transform=axes[1, 2].transAxes)
        axes[1, 2].set_title('Metric Correlations\n(Need more data)')
    
    plt.tight_layout()
    
    # Save the structural analysis plot
    struct_analysis_path = save_dir / "structural_evolution_analysis_shania.png"
    plt.savefig(struct_analysis_path, dpi=160, bbox_inches='tight')
    print(f" Saved structural evolution analysis: {struct_analysis_path}")
    plt.close()
    
    # Generate hypothesis evidence report
    generate_hypothesis_report(generation_data, generations, metrics, save_dir)


def generate_hypothesis_report(generation_data: dict, generations: list, metrics: dict, save_dir: Path):
    """Generate a detailed report on evidence for/against the generative encoding hypothesis."""
    
    report_path = save_dir / "generative_encoding_hypothesis_report_shania.txt"
    
    with open(report_path, 'w') as f:
        f.write("GENERATIVE ENCODING HYPOTHESIS ANALYSIS REPORT\n")
        f.write("=" * 50 + "\n\n")
        f.write("Hypothesis: 'The generative encoding of morphology will promote regularity\n")
        f.write("and reuse of structural motifs that facilitate locomotion efficiency.'\n\n")
        f.write("Note: This analysis examines neural network controller patterns as a proxy\n")
        f.write("for generative encoding principles, since morphology is fixed in this experiment.\n\n")
        
        # Calculate trends and correlations
        if len(generations) > 2:
            # Trend analysis
            fitness_trend = np.polyfit(generations, metrics['fitness'], 1)[0]
            modularity_trend = np.polyfit(generations, metrics['modularity'], 1)[0]
            pattern_reuse_trend = np.polyfit(generations, metrics['pattern_reuse'], 1)[0]
            efficiency_trend = np.polyfit(generations, metrics['efficiency'], 1)[0]
            
            # Correlations
            fitness_pattern_corr = np.corrcoef(metrics['fitness'], metrics['pattern_reuse'])[0, 1]
            fitness_efficiency_corr = np.corrcoef(metrics['fitness'], metrics['efficiency'])[0, 1]
            
            f.write("QUANTITATIVE EVIDENCE:\n")
            f.write("-" * 20 + "\n")
            f.write(f"Generations analyzed: {len(generations)} ({min(generations)} to {max(generations)})\n")
            f.write(f"Final fitness: {metrics['fitness'][-1]:.3f}\n")
            f.write(f"Fitness improvement rate: {fitness_trend:.4f} per generation\n\n")
            
            f.write("PATTERN REUSE EVIDENCE:\n")
            f.write(f"Final repeated patterns: {metrics['pattern_reuse'][-1]}\n")
            f.write(f"Pattern reuse trend: {pattern_reuse_trend:+.3f} patterns/generation\n")
            f.write(f"Fitness-pattern correlation: {fitness_pattern_corr:.3f}\n")
            if fitness_pattern_corr > 0.3:
                f.write("→ SUPPORTS hypothesis: Higher pattern reuse correlates with better fitness\n")
            elif fitness_pattern_corr < -0.3:
                f.write("→ CONTRADICTS hypothesis: Pattern reuse negatively correlates with fitness\n")
            else:
                f.write("→ NEUTRAL: Weak correlation between pattern reuse and fitness\n")
            f.write("\n")
            
            f.write("MODULARITY EVIDENCE:\n")
            f.write(f"Final modularity score: {metrics['modularity'][-1]:.3f}\n")
            f.write(f"Modularity trend: {modularity_trend:+.4f} per generation\n")
            if modularity_trend > 0.001:
                f.write("→ SUPPORTS hypothesis: Increasing functional modularity over time\n")
            elif modularity_trend < -0.001:
                f.write("→ CONTRADICTS hypothesis: Decreasing functional modularity over time\n")
            else:
                f.write("→ NEUTRAL: Stable modularity (neither increasing nor decreasing)\n")
            f.write("\n")
            
            f.write("EFFICIENCY EVIDENCE:\n")
            f.write(f"Final connection efficiency: {metrics['efficiency'][-1]:.3f}\n")
            f.write(f"Efficiency trend: {efficiency_trend:+.4f} per generation\n")
            f.write(f"Fitness-efficiency correlation: {fitness_efficiency_corr:.3f}\n")
            if fitness_efficiency_corr > 0.3:
                f.write("→ SUPPORTS hypothesis: Higher efficiency correlates with better fitness\n")
            elif fitness_efficiency_corr < -0.3:
                f.write("→ CONTRADICTS hypothesis: Efficiency negatively correlates with fitness\n")
            else:
                f.write("→ NEUTRAL: Weak correlation between efficiency and fitness\n")
            f.write("\n")
            
            # Overall assessment
            f.write("OVERALL ASSESSMENT:\n")
            f.write("-" * 18 + "\n")
            
            support_count = 0
            contradict_count = 0
            
            if fitness_pattern_corr > 0.3: support_count += 1
            elif fitness_pattern_corr < -0.3: contradict_count += 1
            
            if modularity_trend > 0.001: support_count += 1
            elif modularity_trend < -0.001: contradict_count += 1
            
            if fitness_efficiency_corr > 0.3: support_count += 1
            elif fitness_efficiency_corr < -0.3: contradict_count += 1
            
            if support_count > contradict_count:
                f.write("CONCLUSION: Evidence SUPPORTS the generative encoding hypothesis\n")
                f.write(f"Supporting indicators: {support_count}, Contradicting indicators: {contradict_count}\n")
            elif contradict_count > support_count:
                f.write("CONCLUSION: Evidence CONTRADICTS the generative encoding hypothesis\n")
                f.write(f"Supporting indicators: {support_count}, Contradicting indicators: {contradict_count}\n")
            else:
                f.write("CONCLUSION: Evidence is MIXED or INCONCLUSIVE\n")
                f.write(f"Supporting indicators: {support_count}, Contradicting indicators: {contradict_count}\n")
                
        else:
            f.write("INSUFFICIENT DATA: Need more generations for trend analysis\n")
        
        f.write("\n")
        f.write("DETAILED GENERATION DATA:\n")
        f.write("-" * 25 + "\n")
        f.write("Gen | Fitness | Patterns | Modularity | Efficiency | Sparsity\n")
        f.write("-" * 60 + "\n")
        
        for i, gen in enumerate(generations):
            f.write(f"{gen:3d} | {metrics['fitness'][i]:7.3f} | {metrics['pattern_reuse'][i]:8d} | "
                   f"{metrics['modularity'][i]:10.3f} | {metrics['efficiency'][i]:10.3f} | {metrics['sparsity'][i]:8.3f}\n")
    
    print(f" Saved hypothesis evidence report: {report_path}")


def main():
    # Load body graph and elite 
    with ELITE_BRAIN_JSON.open("r") as f:
        elite_data = json.load(f)
    elite = np.array(elite_data["genome"], dtype=np.float32)

    assert elite.size == GENOME_SIZE, (
        f"Elite genome length {elite.size} != expected {GENOME_SIZE}. "
        f"(Check INPUT_SIZE/HIDDEN_SIZE/OUTPUT_SIZE or the saved genome.)"
    )

    # initialize generation 0 for a population
    gen0 = make_gen0_population(elite, POPULATION_SIZE, INITIAL_WEIGHT_RANGE)

    best_overall = {
        "genome": elite.copy(),
        "total": -np.inf,
        "comps": {name: 0.0 for name, _ in TERRAIN_SPAWNS},
        "gen": -1,
    }

    # Initialize generation data storage
    generation_data = {}
    
    # print("\n[Gen 0] Evaluating custom populatiuon")  # Commented out: superfluous
    total_scores_g0 = []
    best_total_g0 = -np.inf
    best_comps_g0 = {}
    best_genome_g0 = None
    best_paths_g0 = None

    # Add progress tracking for generation 0 evaluation
    for i, cand in track(enumerate(gen0), description="[Gen 0] Evaluating initial population", total=len(gen0)):
        tot, comps = evaluate_multi_terrain(cand, SIMULATION_STEPS)
        total_scores_g0.append(tot)
        if tot > best_total_g0:
            best_total_g0 = tot
            best_comps_g0 = comps
            best_genome_g0 = cand.copy()
        if tot > best_overall["total"]:
            best_overall.update({"genome": cand.copy(), "total": tot, "comps": comps, "gen": 0})

    # Record best robot path for generation 0
    if best_genome_g0 is not None:
        _, _, best_paths_g0 = evaluate_multi_terrain(best_genome_g0, SIMULATION_STEPS, record_paths=True)
    
    # Analyze network structure for generation 0
    network_analysis_g0 = None
    if best_genome_g0 is not None:
        network_analysis_g0 = analyze_network_structure(best_genome_g0, INPUT_SIZE, OUTPUT_SIZE)
    
    # Store generation 0 data
    generation_data[0] = {
        "best_genome": best_genome_g0,
        "best_fitness": best_total_g0,
        "fitness_components": best_comps_g0,
        "robot_paths": best_paths_g0,
        "network_analysis": network_analysis_g0
    }

    print(f"[Gen 0] Best total={best_total_g0:.3f}, comps={ {k: round(v, 3) for k, v in best_comps_g0.items()} }")

    # EvoTorch Problem 
    problem = Problem(
        "max",
        evotorch_eval,
        solution_length=int(GENOME_SIZE),
        dtype=torch.float32,
        initial_bounds=(-INITIAL_WEIGHT_RANGE, INITIAL_WEIGHT_RANGE),
    )

    # ERROR REPLACEMENT
    # problem = Problem(
    #     objective_sense="max",
    #     objective=evotorch_eval,
    #     solution_length=int(GENOME_SIZE),
    #     dtype=torch.float32,
    #     initial_bounds=(-INITIAL_WEIGHT_RANGE, INITIAL_WEIGHT_RANGE),
    # )

    # CMA-ES 
    searcher = CMAES(
        problem,
        popsize=POPULATION_SIZE,
        stdev_init=0.5,
    )

    fitness_history = [best_total_g0]
    per_terrain_history = {name: [best_comps_g0.get(name, 0.0)] for name, _ in TERRAIN_SPAWNS}

    # Create a rich progress bar for the main evolution loop
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TimeElapsedColumn(),
        TimeRemainingColumn(),
        console=None,  # Use default console
    ) as progress:
        evolution_task = progress.add_task("[green]Evolving brains...", total=GENERATIONS)
        
        for gen in range(1, GENERATIONS + 1):
            searcher.step()

            #best-of-gen with per-terrain
            gen_best_total = -np.inf
            gen_best_comps = {}
            gen_best_genome = None

            # Add nested progress bar for population evaluation
            pop_task = progress.add_task(f"[blue]Gen {gen} evaluation", total=len(searcher.population))
            
            for sol in searcher.population:
                g = sol.values.detach().cpu().numpy().astype(np.float32)
                tot, comps = evaluate_multi_terrain(g, SIMULATION_STEPS)
                if tot > gen_best_total:
                    gen_best_total = tot
                    gen_best_comps = comps
                    gen_best_genome = g
                progress.advance(pop_task)

            progress.remove_task(pop_task)  # Clean up nested task

            # Record best robot path for this generation
            gen_best_paths = None
            if gen_best_genome is not None:
                _, _, gen_best_paths = evaluate_multi_terrain(gen_best_genome, SIMULATION_STEPS, record_paths=True)
            
            # Analyze network structure for this generation
            gen_network_analysis = None
            if gen_best_genome is not None:
                gen_network_analysis = analyze_network_structure(gen_best_genome, INPUT_SIZE, OUTPUT_SIZE)
            
            # Store generation data
            generation_data[gen] = {
                "best_genome": gen_best_genome.copy() if gen_best_genome is not None else None,
                "best_fitness": gen_best_total,
                "fitness_components": gen_best_comps.copy(),
                "robot_paths": gen_best_paths,
                "network_analysis": gen_network_analysis
            }

            fitness_history.append(gen_best_total)
            for name, _ in TERRAIN_SPAWNS:
                per_terrain_history[name].append(gen_best_comps.get(name, 0.0))

            if gen_best_total > best_overall["total"]:
                best_overall.update({"genome": gen_best_genome.copy(), "total": gen_best_total, "comps": gen_best_comps, "gen": gen})
                print(f"New BEST gen:{gen}, total={gen_best_total:.3f}")  # Keep important updates
            
            # Update main progress bar with current best info
            progress.update(evolution_task, description=f"[green]Evolving brains... Best: {best_overall['total']:.3f}")
            progress.advance(evolution_task)

    # Save best genome
    save_dir = Path(r"ImprovementRuns/MultiTerrain")
    save_dir.mkdir(parents=True, exist_ok=True)

    json_filename = f"best_genome_POP{POPULATION_SIZE}_GEN{GENERATIONS}_3terrains_shania.json"
    json_path = save_dir / json_filename

    save_best_genome(json_path, best_overall["genome"], POPULATION_SIZE, GENERATIONS, int(best_overall["gen"]))
    print(f"\n[RESULT] Best total={best_overall['total']:.3f} from generation {best_overall['gen']}")
    print(f" Per-terrain: { {k: round(v,3) for k, v in best_overall['comps'].items()} }")
    print(f" Saved best genome: {json_path}")

    # Save comprehensive generation data (including robot paths and fitness for all generations)
    generation_data_filename = f"generation_data_POP{POPULATION_SIZE}_GEN{GENERATIONS}_3terrains_shania.json"
    generation_data_path = save_dir / generation_data_filename
    save_generation_data(generation_data_path, generation_data)
    print(f" Saved generation data: {generation_data_path}")

    # Create robot path visualizations
    plot_robot_paths(generation_data, save_dir)

    # Analyze structural evolution for generative encoding hypothesis
    analyze_structural_evolution(generation_data, save_dir)

    # Plot fitness progress
    plt.figure(figsize=(8, 5))
    plt.plot(fitness_history, marker="o", linestyle="-", label="Total (best-of-gen)")
    for name, series in per_terrain_history.items():
        plt.plot(series, linestyle="--", label=name)
    plt.xlabel("Generation")
    plt.ylabel("Fitness (sum of projected progress)")
    plt.title("Evolution Progress (CMA-ES) — Brain Only, 3 Terrains")
    plt.grid(True)
    plt.legend()
    plot_path = save_dir / "fitness_progress_3terrains_shania.png"
    plt.savefig(plot_path, dpi=160)
    print(f" Saved plot: {plot_path}")


if __name__ == "__main__":
    main()

